In [12]:
import cPickle as pickle
a = pickle.load(open('trees_test.pkl','rb'))

In [22]:
a

[Tree('N1', []),
 Tree('', [Tree('N2', []), Tree('N1', [])]),
 Tree('A1', []),
 Tree('A2', []),
 Tree('A1', [Tree('A1', []), Tree('I1', [])]),
 Tree('I2', []),
 Tree('I1', [])]

In [129]:
d = pickle.load(open('dicts_test.pkl','rb'))
d['bin']
v = pickle.load(open('vects_test.pkl','rb'))
v['bin']
t = pickle.load(open('trees_test.pkl','rb'))
t

[Tree('N1', []),
 Tree('', [Tree('N2', []), Tree('N1', [])]),
 Tree('A1', []),
 Tree('A2', []),
 Tree('A1', [Tree('A1', []), Tree('I1', [])]),
 Tree('I2', []),
 Tree('I1', [])]

In [121]:
v = pickle.load(open('kernels_test.pkl','rb'))
y = pickle.load(open('labels_test.pkl','rb'))
print y
print v['rbf']['bin']

[0 0 1 1 2 2 2]
[[ 1.          0.75147729  0.75147729  0.75147729  0.65143906  0.75147729
   0.75147729]
 [ 0.75147729  1.          0.56471812  0.56471812  0.48954166  0.56471812
   0.56471812]
 [ 0.75147729  0.56471812  1.          0.75147729  0.8668779   0.75147729
   0.75147729]
 [ 0.75147729  0.56471812  0.75147729  1.          0.65143906  0.75147729
   0.75147729]
 [ 0.65143906  0.48954166  0.8668779   0.65143906  1.          0.65143906
   0.8668779 ]
 [ 0.75147729  0.56471812  0.75147729  0.75147729  0.65143906  1.
   0.75147729]
 [ 0.75147729  0.56471812  0.75147729  0.75147729  0.8668779   0.75147729
   1.        ]]


In [97]:
from sklearn.neighbors import KNeighborsClassifier

clf = KNeighborsClassifier(n_neighbors=5,metric='precomputed')
clf.fit(v['eucl_dist'][0],y)
clf.predict(v['eucl_dist'][0][2:4])

array([1, 1])

In [98]:
v

{'cos_sim': [array([[ 1.        ,  0.57735027,  0.        ,  0.        ,  0.        ,
           0.        ,  0.        ],
         [ 0.57735027,  1.        ,  0.        ,  0.        ,  0.        ,
           0.        ,  0.        ],
         [ 0.        ,  0.        ,  1.        ,  0.        ,  0.70710678,
           0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
           0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.70710678,  0.        ,  1.        ,
           0.        ,  0.70710678],
         [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
           1.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  0.        ,  0.70710678,
           0.        ,  1.        ]]),
  array([[ 1.        ,  0.57735027,  0.        ,  0.        ,  0.        ,
           0.        ,  0.        ],
         [ 0.57735027,  1.        ,  0.        ,  0.        ,  0.        ,
           0.   

In [102]:
b=None
if(b is None):
    print 'kldjfl'

kldjfl


In [106]:
from nltk import Tree
t=Tree.fromstring("(A)")
t2=Tree.copy(t,deep=True)

In [1]:
from os import listdir
from os.path import join as joinpath

In [2]:
path0 = 'data/narrative/'
path1 = 'data/argumentative/'
path2 = 'data/informative/'
doclist0 = [joinpath(path0, fname) for fname in listdir(path0) if fname.endswith('.xml')]
doclist1 = [joinpath(path1, fname) for fname in listdir(path1) if fname.endswith('.xml')]
doclist2 = [joinpath(path2, fname) for fname in listdir(path2) if fname.endswith('.xml')]

In [3]:
def get_docs(doclist):
    docs = []
    for f in doclist:
        doc = open(f, 'r')
        content = doc.read()
        docs.append((content,f))
    return docs

In [4]:
docs0 = get_docs(doclist0)
docs1 = get_docs(doclist1)
docs2 = get_docs(doclist2)

In [37]:
import BeautifulSoup as BeautifulSoup
import copy
import numpy as np

def build_count_tags_vect(doc):
    soup = BeautifulSoup.BeautifulSoup(doc)
    tags = soup.findAll('pos')
    dico = {}
    for t in tags:
        if t.text not in dico.keys():           
            dico[t.text] = 1
        else:
            dico[t.text] += 1
    return dico

def build_norm_tags_vects(count_vect):
    c_ve = copy.deepcopy(count_vect)
    print 'deepcopied'
    for i in range(len(c_ve)):
        total = np.sum(c_ve[i][0].values())
        for j in c_ve[i][0].keys():
            c_ve[i][0][j] = float(c_ve[i][0][j])/total        
    return c_ve

def build_count_tags_vects(docs):
    return [(build_count_tags_vect(doc[0]),doc[1]) for doc in docs]

In [8]:
narr = build_count_tags_vects(docs0)
arg = build_count_tags_vects(docs1)
inf = build_count_tags_vects(docs2)

In [9]:
y_nar = [0 for t in narr]
y_arg = [1 for t in arg]
y_inf = [2 for t in inf]

In [16]:
docs = narr + arg + inf
y = y_nar + y_arg + y_inf
import cPickle as pickle
pickle.dump(docs,open('pos_count_vects.pkl','w'))
pickle.dump(y,open('y_pos_count_vects.pkl','w'))

In [42]:
norm = build_norm_tags_vects(docs)
pickle.dump(norm,open('pos_norm_vects.pkl','w'))

deepcopied
